name: Auto Assign PR

on:
  pull_request:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Assign PR to author
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo, number } = context.issue;
            const author = context.payload.pull_request.user.login;

            await github.rest.issues.addAssignees({
              owner,
              repo,
              issue_number: number,
              assignees: [author]
            });

            console.log(`Assigned PR #${number} to ${author}`);
